# Generated by Django 4.2.5 on 2023-09-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.so', verbose_name='So'),
        ),
    ]
